Sources: 
- https://machinelearningmastery.com/singular-value-decomposition-for-machine-learning/

Contents:

**27th Feb 2017**
1. Calculate Singular-Value Decomposition
2. Reconstruct Matrix from SVD

**28th Feb 2017**
3. SVD for Pseudoinverse
4. SVD for Dimensionality Reduction
5. Self Implemented SVD

# 1. Calculate Singular-Value Decomposition using scipy

In [2]:
from numpy import array
from scipy.linalg import svd

In [12]:
A = array([[5,3],[1,2],[3,5]])
A.shape

(3, 2)

In [4]:
# Singular-value decomposition

U, s, V = svd(A)

In [5]:
U

array([[-0.67912302,  0.73179502, -0.0571662 ],
       [-0.25817155, -0.31104042, -0.91465912],
       [-0.68712398, -0.60640738,  0.40016337]])

In [6]:
s

array([ 8.27859511,  2.11302225])

In [7]:
V

array([[-0.69035368, -0.72347204],
       [ 0.72347204, -0.69035368]])

# 2. Reconstruct Matrix from SVD

U, s, and V elements returned from the svd() cannot be multiplied directly 

s vector must be converted into a diagonal matrix using the diag() function

In [8]:
from numpy import diag
from numpy import dot
from numpy import zeros

For multiplication we require that

```U (m x m) . Sigma (m x n) . V^T (n x n)```

In case rectangular original matrix

In [9]:
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# (rows, columns)
Sigma

# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
Sigma

array([[ 8.27859511,  0.        ],
       [ 0.        ,  2.11302225],
       [ 0.        ,  0.        ]])

above complication with the Sigma diagonal only exists with the case where m and n are not equal.

In case of square, we can directly use

```diag(s)```

In [10]:
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[ 5.  3.]
 [ 1.  2.]
 [ 3.  5.]]


# 3. SVD for Pseudoinverse

# 4. SVD for Dimensionality Reduction

In [18]:
from numpy.linalg import matrix_rank

In [22]:
A = array([
	[1,2,3,4,5,6,7,8,9,10],
	[11,12,13,14,15,16,17,18,19,20],
	[21,22,23,24,25,26,27,28,29,30]])
print('Original Matrix', 'Rank is',matrix_rank(A))
print(A)
# Singular-value decomposition
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[0], :A.shape[0]] = diag(s)
# select
n_elements = 2
Sigma = Sigma[:, :n_elements]
V = V[:n_elements, :]
# reconstruct
B = U.dot(Sigma.dot(V))
print('Reconstructed Matrix', 'Rank is',matrix_rank(B))
print(B)
# transform
T = U.dot(Sigma)
print(T)
T = A.dot(V.T)
print(T)

Original Matrix Rank is 2
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
Reconstructed Matrix Rank is 2
[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [ 11.  12.  13.  14.  15.  16.  17.  18.  19.  20.]
 [ 21.  22.  23.  24.  25.  26.  27.  28.  29.  30.]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
[[-18.52157747   6.47697214]
 [-49.81310011   1.91182038]
 [-81.10462276  -2.65333138]]
