https://rockt.github.io/2018/04/30/einsum

Inner & outer products: https://www.youtube.com/watch?v=FCmH4MqbFGs

FastAI 8 https://forums.fast.ai/t/lesson-8-notes/41442/22

This is one of my random practice notebook. I try to recreate what I am learning from FastAI without refering the original notes.

The reason to release this publish is to get into the habit of "To be useful: Do everything in public and for the public": https://www.youtube.com/watch?v=5UbixCFJ2DA  and to build my deep learning momentum.


Most/all content/ideas from this notebook are not my own but from source are links above. #NoPlagiarism

In [0]:
import torch

a = torch.arange(6).reshape(2,3)
a, a.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), torch.Size([2, 3]))

# Matrix Transpose

In [0]:
b = torch.einsum('ij->ji',a) #get something of dimension ij and give dimension ji
b, b.shape

(tensor([[0, 3],
         [1, 4],
         [2, 5]]), torch.Size([3, 2]))

# Sum

In [0]:
b = torch.einsum('ij->',a) #get something of dimension ij and give something that has no dimension
b, b.shape

(tensor(15), torch.Size([]))

## Code Sum

In [0]:
b = torch.einsum('ij->j',a) 
"""
i is row, j is column


"""
a, b, b.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([3, 5, 7]), torch.Size([3]))

# Row Sum

In [0]:
b = torch.einsum('ij->i',a) 
"""
i is row, j is column
"""
a, b, b.shape

(tensor([[0, 1, 2],
         [3, 4, 5]]), tensor([ 3, 12]), torch.Size([2]))

# Matrix Vector Multiplication

In [0]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [0]:
c = torch.arange(3)
c.shape

torch.Size([3])

In [0]:
b = torch.einsum('ij,j->i',a,c)
b

tensor([ 5, 14])

# Matrix Matrix Multiplication

In [0]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [0]:
c = torch.arange(3*4).view(3,4)
c

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [0]:
b = torch.einsum('ij,jk->ik',a,c)
b

tensor([[20, 23, 26, 29],
        [56, 68, 80, 92]])

In [0]:
a@c

tensor([[20, 23, 26, 29],
        [56, 68, 80, 92]])

# Dot Product between Vectors

In [0]:
q = torch.arange(3)
q, q.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [0]:
w = torch.arange(3)
w, w.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [0]:
e = torch.einsum('i,i->',q,w) # get something which has same dimension and return something which has no dimension
e

tensor(5)

In [0]:
q@w

tensor(5)

# Dot Product Between Matrix

In [0]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [0]:
c

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [0]:
b = torch.einsum('ij,jk->',a,c)
b

tensor(394)

In [0]:
(a@c).sum()

tensor(394)

# HADAMARD PRODUCT (Element vise multiplication)

In [0]:
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [0]:
b = torch.einsum('ij,ij->ij',a,a)
b

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

In [0]:
a * a

tensor([[ 0,  1,  4],
        [ 9, 16, 25]])

# Outer product!

vector u
vector v

both have same dimension (3,1)

Inner product = Dot Product

u.T  times v

1,3 ......3,1 -> 1,1

Outer product

u times v.T

3,1.... 1,3 -> 3,3



In [0]:
from IPython.display import Math, HTML
html = """<iframe width="560" height="315" src="https://www.youtube.com/embed/FCmH4MqbFGs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>"""
display(HTML(html))

In [0]:
q, q.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [0]:
w, w.shape

(tensor([0, 1, 2]), torch.Size([3]))

In [0]:
q, w = q.reshape(3,1), w.reshape(3,1)
q.shape,w.shape

(torch.Size([3, 1]), torch.Size([3, 1]))

In [0]:
#error
e = torch.einsum('ij,ij->ii',q,w)
e

RuntimeError: ignored

In [0]:
e = torch.einsum('ij,kl->ik',q,w)
e

tensor([[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]])

In [0]:
# we can also do it without reshape

q = torch.arange(3)
w = torch.arange(3)

e = torch.einsum('i,j->ij',q,w)
e

tensor([[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]])

## Batch matrix element wise multiplication 

In [0]:
a = torch.rand(3,3,3)

# batchsize, ...

c = torch.rand(3,3)

In [0]:
b = torch.einsum('ijk,jk->ijk',a,c)
b

tensor([[[0.0312, 0.1098, 0.1939],
         [0.1593, 0.0412, 0.5006],
         [0.0553, 0.4350, 0.6249]],

        [[0.0486, 0.2683, 0.0245],
         [0.2628, 0.5035, 0.5046],
         [0.0187, 0.4950, 0.7195]],

        [[0.0324, 0.1774, 0.2731],
         [0.2224, 0.3343, 0.5363],
         [0.0919, 0.0486, 0.3506]]])

In [0]:
c.expand_as(a)

tensor([[[0.0526, 0.5375, 0.4384],
         [0.2721, 0.5066, 0.6326],
         [0.1299, 0.7080, 0.9857]],

        [[0.0526, 0.5375, 0.4384],
         [0.2721, 0.5066, 0.6326],
         [0.1299, 0.7080, 0.9857]],

        [[0.0526, 0.5375, 0.4384],
         [0.2721, 0.5066, 0.6326],
         [0.1299, 0.7080, 0.9857]]])

In [0]:
a * c

tensor([[[0.0312, 0.1098, 0.1939],
         [0.1593, 0.0412, 0.5006],
         [0.0553, 0.4350, 0.6249]],

        [[0.0486, 0.2683, 0.0245],
         [0.2628, 0.5035, 0.5046],
         [0.0187, 0.4950, 0.7195]],

        [[0.0324, 0.1774, 0.2731],
         [0.2224, 0.3343, 0.5363],
         [0.0919, 0.0486, 0.3506]]])

# Batch Matrix product

In [0]:
a

tensor([[[0.5931, 0.2042, 0.4424],
         [0.5853, 0.0813, 0.7914],
         [0.4255, 0.6144, 0.6339]],

        [[0.9238, 0.4991, 0.0559],
         [0.9657, 0.9937, 0.7977],
         [0.1442, 0.6991, 0.7299]],

        [[0.6153, 0.3300, 0.6230],
         [0.8174, 0.6598, 0.8477],
         [0.7071, 0.0686, 0.3557]]])

In [0]:
c

tensor([[0.0526, 0.5375, 0.4384],
        [0.2721, 0.5066, 0.6326],
        [0.1299, 0.7080, 0.9857]])

In [0]:
b = torch.einsum('ijk,kl->ijl',a,c)
b

tensor([[[0.1443, 0.7355, 0.8252],
         [0.1558, 0.9162, 1.0881],
         [0.2719, 0.9889, 1.2001]],

        [[0.1917, 0.7890, 0.7758],
         [0.4248, 1.5873, 1.8382],
         [0.2926, 0.9485, 1.2249]],

        [[0.2031, 0.9390, 1.0925],
         [0.3327, 1.3739, 1.6113],
         [0.1021, 0.6667, 0.7040]]])

In [0]:
a @ c

tensor([[[0.1443, 0.7355, 0.8252],
         [0.1558, 0.9162, 1.0881],
         [0.2719, 0.9889, 1.2001]],

        [[0.1917, 0.7890, 0.7758],
         [0.4248, 1.5873, 1.8382],
         [0.2926, 0.9485, 1.2249]],

        [[0.2031, 0.9390, 1.0925],
         [0.3327, 1.3739, 1.6113],
         [0.1021, 0.6667, 0.7040]]])

For case studies check: https://rockt.github.io/2018/04/30/einsum