1:41:58



In [0]:
import torch
from torch import nn

In [2]:
data = torch.rand(500,10)
mean, std = data.mean(), data.std()
mean, std

(tensor(0.5045), tensor(0.2906))

In [3]:
def normalize(data,train_mean, train_std): return (data-train_mean)/train_std
data = normalize(data, mean, std)
data.mean(), data.std()

(tensor(-1.1421e-07), tensor(1.))

In [0]:
lin1 = nn.Linear(10,1)

In [5]:
lin1.weight, lin1.weight.shape

(Parameter containing:
 tensor([[-0.2869, -0.0468, -0.0129,  0.1544,  0.2151, -0.3056, -0.2676,  0.2435,
           0.0342,  0.1966]], requires_grad=True), torch.Size([1, 10]))

In [6]:
lin1.bias

Parameter containing:
tensor([0.0829], requires_grad=True)

In [0]:
from torch.nn import init

In [17]:
init.kaiming_normal_(lin1.weight, mode='fan_in',nonlinearity='relu')
init.zeros_(lin1.bias)

Parameter containing:
tensor([0.], requires_grad=True)

In [18]:
lin1.weight.mean(), lin1.weight.std()

(tensor(-0.1063, grad_fn=<MeanBackward0>),
 tensor(0.4827, grad_fn=<StdBackward0>))

In [0]:
import torch.nn.functional as F


In [0]:
output = F.relu(lin1(data))

In [21]:
output.mean(), output.std()

(tensor(0.5689, grad_fn=<MeanBackward0>),
 tensor(0.8471, grad_fn=<StdBackward0>))

In [22]:
lin1 = nn.Linear(10,1)
init.kaiming_uniform_(lin1.weight, mode='fan_out',nonlinearity='relu')
init.zeros_(lin1.bias)

Parameter containing:
tensor([0.], requires_grad=True)

In [23]:

output = F.relu(lin1(data))
output.mean(), output.std()

(tensor(1.6131, grad_fn=<MeanBackward0>),
 tensor(2.4117, grad_fn=<StdBackward0>))