FastAI 8 
https://forums.fast.ai/t/lesson-8-notes/41442/22

http://matrixmultiplication.xyz/

---


This is one of my random practice notebook. I try to recreate what I am learning from FastAI without refering the original notesa. 

Most/all content/ideas from this ntoebook are not my own but from source are links above. #NoPlagiarism

---


In [0]:
import torch

In [2]:
m1 = [
      [1, 2, 3],
      [4, 5, 6],
      [6, 7, 8],
]

m1 = torch.Tensor(m1)
m1, m1.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [6., 7., 8.]]), torch.Size([3, 3]))

In [3]:
m2 = [
      [1], 
      [2], 
      [3],
]
m2 = torch.Tensor(m2)
m2, m2.shape

(tensor([[1.],
         [2.],
         [3.]]), torch.Size([3, 1]))

In [4]:
m1 @ m2

tensor([[14.],
        [32.],
        [44.]])

# Manual

In [5]:
#check if rows of first matrix is equal to columns of second
r1, c1 = m1.shape
r2, c2 = m2.shape
assert c1 == r2

# the resultant matrix shape is rows of first column x columns of second
# creating empty array
result = torch.zeros(r1, c2)

# run and look at matrixmultiplication.xyz to clearly understand what is written below
# i tracks row number of first matrix and row of resultant matrix
#### j tracks columns of first matrix which is equal to rows of second 
######## k tracks columns of second matrix and column of resultant matrix

for i in range(r1):
    for j in range(c1):
        for k in range(c2):
            result[i,k] += m1[i,j] * m2[j,k]

result

tensor([[14.],
        [32.],
        [44.]])

To make this faster we have to vectorize it... remove loops starting from innter most

In [6]:
result = torch.zeros(r1, c2)

for i in range(r1):
    for j in range(c1):
        result[i] = m1[i]*m2[j]
        #for k in range(c2):
        #    result[i,k] += m1[i,j] * m2[j,k]

RuntimeError: ignored

Because of errors I went back and looked at my multiplication loop and then modiefied it so that we can easily remove variable k

In [7]:
m1

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [6., 7., 8.]])

In [8]:
m2

tensor([[1.],
        [2.],
        [3.]])

In [9]:
# get first row of first matrix
i = 0
m1[i]

tensor([1., 2., 3.])

In [13]:
# get first column of second matrix
j = 0
m2[:,j]

tensor([1., 2., 3.])

In [15]:
result = torch.zeros(r1, c2)

# shorten function

for i in range(r1):
    for j in range(c2):
        result[i,j] = (m1[i]*m2[:,j]).sum()

result

tensor([[14.],
        [32.],
        [44.]])

Even simpler:

Einsum

FastAI 8 
https://forums.fast.ai/t/lesson-8-notes/41442/22

In [20]:
result = torch.einsum('ik,kj->ij',m1,m2)
result

tensor([[14.],
        [32.],
        [44.]])

Simplest:

In [21]:
result = m1@m2
result

tensor([[14.],
        [32.],
        [44.]])

In [23]:
result = m1.matmul(m2)
result

tensor([[14.],
        [32.],
        [44.]])

The reason to use Pytorch implementation is that it is about 50,000 times faster than regular python.

For details check out:

FastAI 8 
https://forums.fast.ai/t/lesson-8-notes/41442/22