In [0]:
import torch

In [0]:
x = torch.ones(2,2)

In [3]:
x

tensor([[1., 1.],
        [1., 1.]])

In [4]:
x.shape

torch.Size([2, 2])

In [5]:
x.dtype

torch.float32

In [0]:
y = x.new_ones((2,2))

In [7]:
y

tensor([[1., 1.],
        [1., 1.]])

In [8]:
y.shape

torch.Size([2, 2])

In [9]:
y.size()

torch.Size([2, 2])

In [11]:
y.data

tensor([[1., 1.],
        [1., 1.]])

In [0]:
t = torch.randn(2,3, dtype=torch.double)

In [13]:
t

tensor([[-0.1101, -1.4713, -0.5243],
        [-0.5705,  0.7466, -0.1863]], dtype=torch.float64)

In [14]:
torch.empty(3,2)

tensor([[1.1519e-35, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00]])

In [21]:
result = torch.empty_like(t)
torch.add(t,t, out = result)

tensor([[-0.2202, -2.9426, -1.0486],
        [-1.1410,  1.4933, -0.3725]], dtype=torch.float64)

In [22]:
result

tensor([[-0.2202, -2.9426, -1.0486],
        [-1.1410,  1.4933, -0.3725]], dtype=torch.float64)

In [25]:
t.view(-1,2)

tensor([[-0.1101, -1.4713],
        [-0.5243, -0.5705],
        [ 0.7466, -0.1863]], dtype=torch.float64)

In [26]:
t

tensor([[-0.1101, -1.4713, -0.5243],
        [-0.5705,  0.7466, -0.1863]], dtype=torch.float64)

In [28]:
t.mean().item()

-0.3526406547273531

In [0]:
t_num = t.numpy()

In [33]:
t_num = t_num*2
t_num

array([[-0.44038389, -5.8852472 , -2.09718127],
       [-2.28204077,  2.98656565, -0.74508823]])

In [34]:
t

tensor([[-0.1101, -1.4713, -0.5243],
        [-0.5705,  0.7466, -0.1863]], dtype=torch.float64)

In [0]:
t_num[0,0] = 200

In [40]:
t_num

array([[ 2.00000000e+02, -1.47131180e+00, -5.24295318e-01],
       [-5.70510193e-01,  7.46641413e-01, -1.86272057e-01]])

In [41]:
t

tensor([[ 2.0000e+02, -1.4713e+00, -5.2430e-01],
        [-5.7051e-01,  7.4664e-01, -1.8627e-01]], dtype=torch.float64)

In [0]:
ten = torch.tensor([3,2,4])

In [0]:
import numpy as np

In [0]:
np_ten = np.array([1,2,3])

In [45]:
np_ten

array([1, 2, 3])

In [46]:
torch.from_numpy(np_ten)

tensor([1, 2, 3])

In [47]:
torch.cuda.is_available()

True

In [0]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [55]:
device

device(type='cuda')

In [56]:
x

tensor([[1., 1.],
        [1., 1.]])

In [58]:
x.to(device)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [59]:
x

tensor([[1., 1.],
        [1., 1.]])

In [0]:
h = torch.tensor([1.], requires_grad=True)

In [62]:
h

tensor([1.], requires_grad=True)

In [0]:
y=h+20

In [64]:
y

tensor([21.], grad_fn=<AddBackward0>)

In [65]:
y.grad_fn

In [0]:
y.grad

In [0]:
y.backward()

In [79]:
h

tensor([0.7000], grad_fn=<SubBackward0>)

In [84]:
while y.item()!=0 and h.grad:
    y = h+20
    y.backward()
    h= h -0.1*h.grad
    print(f'y={y} h={h}')

y=tensor([21.], grad_fn=<AddBackward0>) h=tensor([0.8000], grad_fn=<SubBackward0>)


In [91]:
y = h+20
y.backward()
h= h -0.1*h.grad
print(f'y={y} h={h}')
h.grad.data.zero_()

TypeError: ignored

In [88]:
y = h+20
y

tensor([20.8000], grad_fn=<AddBackward0>)

In [92]:
y.backward()
h.grad.data.zero_()

AttributeError: ignored

In [93]:
y.data.norm()

tensor(20.8000)

In [96]:
with torch.no_grad():
    print(h.requires_grad)

True
