http://matrixmultiplication.xyz/



In [0]:
import torch

In [0]:
m1 = [
      [1, 2, 3],
      [4, 5, 6],
      [6, 7, 8],
]

m1 = torch.Tensor(m1)
m1, m1.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [6., 7., 8.]]), torch.Size([3, 3]))

In [0]:
m2 = [
      [1], 
      [2], 
      [3],
]
m2 = torch.Tensor(m2)
m2, m2.shape

(tensor([[1.],
         [2.],
         [3.]]), torch.Size([3, 1]))

In [0]:
m1 @ m2

tensor([[14.],
        [32.],
        [44.]])

# Manual

In [0]:
#check if rows of first matrix is equal to columns of second
r1, c1 = m1.shape
r2, c2 = m2.shape
assert c1 == r2

# the resultant matrix shape is rows of first column x columns of second
# creating empty array
result = torch.zeros(r1, c2)

# run and look at matrixmultiplication.xyz to clearly understand what is written below
# i tracks row number of first matrix and row of resultant matrix
#### j tracks columns of first matrix which is equal to rows of second 
######## k tracks columns of second matrix and column of resultant matrix

for i in range(r1):
    for j in range(c1):
        for k in range(c2):
            result[i,k] += m1[i,j] * m2[j,k]

result

tensor([[14.],
        [32.],
        [44.]])

To make this faster we have to vectorize it... remove loops starting from innter most

In [0]:
result = torch.zeros(r1, c2)

for i in range(r1):
    for j in range(c1):
        result[i] = m1[i]*m2[j]
        #for k in range(c2):
        #    result[i,k] += m1[i,j] * m2[j,k]

RuntimeError: ignored