In [4]:
from scipy.linalg import svd
import numpy as np

# View last line

In [59]:
A = np.random.randn(3,2)

In [60]:
A

array([[-0.36911951,  1.06939596],
       [ 0.59249793,  2.46478963],
       [-0.65898903, -0.96256054]])

In [61]:
U,d,Vt = svd(A)

In [62]:
U

array([[-0.32984765,  0.80658925, -0.49052453],
       [-0.86809343, -0.05497153,  0.49334767],
       [ 0.37096404,  0.58855069,  0.71832705]])

In [63]:
d

array([ 2.91982456,  0.73587534])

In [64]:
Vt

array([[-0.21818146, -0.97590822],
       [-0.97590822,  0.21818146]])

In [65]:
sigma = np.zeros((U.shape[0], U.shape[1]))

In [66]:
sigma

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [68]:
sigma[:d.shape[0], :d.shape[0]] = np.diag(d)

In [69]:
sigma

array([[ 2.91982456,  0.        ,  0.        ],
       [ 0.        ,  0.73587534,  0.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [72]:
Vt.dot(sigma.dot(U))

ValueError: shapes (2,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

In [6]:
# Reconstruct SVD
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd
# define a matrix
A = array([[1, 0 ,2], [3, 2,4], [5,2, 6],[1, 2,2]])
print(A)
# Singular-value decomposition
U, s, V = svd(A)
# create m x n Sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
# reconstruct matrix
B = U.dot(Sigma.dot(V))
print(B)

[[1 0 2]
 [3 2 4]
 [5 2 6]
 [1 2 2]]
[[  1.00000000e+00   3.01623567e-16   2.00000000e+00]
 [  3.00000000e+00   2.00000000e+00   4.00000000e+00]
 [  5.00000000e+00   2.00000000e+00   6.00000000e+00]
 [  1.00000000e+00   2.00000000e+00   2.00000000e+00]]


In [3]:
C = A
A

array([[1, 0, 2],
       [3, 2, 4],
       [5, 2, 6],
       [0, 2, 2]])

array([[1, 0, 2],
       [3, 2, 4],
       [5, 2, 6],
       [1, 2, 2]])

In [111]:
#U (m x m) . Sigma (m x n) . V^T (n x n)

C = np.zeros((A.shape[0]+6, A.shape[1]+6))

In [113]:
C[:A.shape[0],:A.shape[1]] = A

In [114]:
C

array([[ 1.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 5.,  2.,  6.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  2.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])