In [3]:
import numpy as np

Hello

In [4]:
array = np.random.rand(3,2)

In [ ]:
array

In [4]:
array - 2.5

array([[-2.15269837, -1.88441586],
       [-2.08844023, -1.71395842],
       [-1.50740739, -2.29440259]])

In [15]:
array!=0

array([[ True,  True],
       [ True,  True],
       [ True,  True]], dtype=bool)

In [16]:
array[array!=0] -= 4

In [17]:
array

array([[-3.65269837, -3.38441586],
       [-3.58844023, -3.21395842],
       [-3.00740739, -3.79440259]])

In [26]:
array2 = np.zeros((3,2))

In [27]:
array2

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [28]:
array2[array2==0] -=2.5

In [29]:
array2

array([[-2.5, -2.5],
       [-2.5, -2.5],
       [-2.5, -2.5]])